mrousavy/react-native-mmkv

.gitmodules
android/CMakeLists.txt
package-lock.json
package.json

Build a precompiled .aar file so you don't have to build the native C++ files anymore.
* Increases compilation time
* You don't need NDK installed
* Fixes #4

Android .aar

---

android/cpp-adapter.cpp
ios/Mmkv.mm
src/index.ts

Adds the clear all method to delete all keys. This avoid having to loop through all keys and call delete.

Add clearAll

---

ios/Mmkv.mm

fixes #24 
this is a temporary fix to avoid a `setBridge:` race condition on iOS and will be fully fixed when TurboModules land

fix: Fix race condition crash on iOS

---

example/metro.config.js

`metro-config/src/defaults/blacklist` was renamed to `metro-config/src/defaults/exclusionList` in this commit: [facebook/metro@3e2d911](https://github.com/facebook/metro/commit/3e2d9116d8a7f2580dcda51990cca5b3d98a81ff#diff-a6e36af38cd6fde5360c601ce8f2f02e4e6b350b7fea9b0f049ab63f3b8f5709).
example project is not working because of this, the PR just fix it.

Renaming import from blacklist to exclusionList

---

scripts/bootstrap.js

This PR adds the same fix from https://github.com/callstack/react-native-builder-bob/commit/8bac4d4 I added over at `vision-camera-image-labeler` to make the `yarn` override script work on Windows.

fix: make bootstrap script work on windows

---

src/MMKV.ts

Declared global functions that come from JSI to remove type error and `@ts-expect-error`.

fix: typescript for JSI global functions

---

android/build.gradle
example/ios/Podfile.lock

The problem:
Rebuild commands like
`./gradlew clean buildDebug`
`./gradlew clean buildRelease`
`./gradlew clean assembleDebug`
`./gradlew clean assembleRelease`
and other similar commands throw the gradle exception which is described [here](https://github.com/mrousavy/react-native-mmkv/issues/145)
That is possible solution from [here](https://github.com/ammarahm-ed/react-native-simple-jsi/issues/1#issuecomment-930287524).
Checked on example project and looks like it works

Fix: Android rebuild command

---

src/hooks.ts

When we initially call useMMKV, `lastConfiguration` is initialized, causing `!isConfigurationEqual(lastConfiguration.current, configuration)` to be `false` and we don't save a new MMKV instance. The solution I propose should fix this issue.

Fix bug in useMMKV

---

android/build.gradle

The extract tasks are being incorrectly added to clean tasks (`externalNativeBuild{Debug|Release}Clean`) which causes files to be missing when running `./gradlew clean assembleRelease`.

Fix extract tasks being added to clean tasks

---

README.md
example/src/Benchmarks.ts
src/MMKV.ts
src/createMMKV.ts
src/createMMKV.web.ts
tsconfig.json

Adds support for MMKV on the Web.
This uses the [`localStorage` API](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) instead of MMKV as a "native" instance.
On _native_ (iOS/Android) nothing changes.
Solves #11

feat: Web support

---

android/CMakeLists.txt
android/build.gradle

When building RN from source, the prebuilt artifacts will be located somewhere else. This detects source build by looking for existence of ReactAndroid project and if it is the case it will get artifacts from the right folder. We also need to depend on ReactAndroid build tasks to make sure the artifacts are built first.

feat: support source builds on android

---

src/MMKV.ts

Implements `toString()` and `toJSON()` for MMKV instances so you can log them.
Example:
```ts
const storage = new MMKV();
console.log(storage.toString());  // <-- toString
console.log(storage);             // <-- toJSON
```
```sh
MMKV (mmkv.default): [5555, xyyyyy, test]     # <-- toString
{"mmkv.default": ["5555", "xyyyyy", "test"]}  # <-- toJSON
```

feat: `toString()` and `toJSON()`

---

android/CMakeLists.txt

This PR fixes a niche problem with CMake when trying to build version `>= 2.0.0` of this library with React Native `< 0.66.0` on Windows.
Because Windows uses backslashes in paths and `add_library()` interprets these verbatim as escape characters CMake would run into the following error:
```
CMake Error at C:\Users\yfunk\...\my-app\node_modules\react-native-mmkv\android\CMakeLists.txt:22 (add_library):
Syntax error in cmake code when parsing string
C:\Users\yfunk\...\my-app\node_modules/react-native/ReactCommon/jsi/jsi/jsi.cpp
Invalid character escape '\U'.
```
I fixed this by using [`file(TO_CMAKE_PATH ...)`](https://cmake.org/cmake/help/latest/command/file.html#to-cmake-path) to set the `INCLUDE_JSI_CPP` variable, since it normalizes all backslashes into forward ones.

fix: normalize `INCLUDE_JSI_CPP` path in cmake

---

docs/WRAPPER_ZUSTAND_PERSIST_MIDDLEWARE.md

Zustand persist middleware accepts synchronous storage methods too, so there is no need for a Promise based definition.
[Zustand Persist Docs](https://github.com/pmndrs/zustand/blob/main/src/middleware/persist.ts#L7)

Convert zustand persist middleware example to Synchronous storage

---

ios/MmkvModule.mm

It is mentioned in main MMKV package that  [MMKV initializeMMKV:nil] function should always initialize in a main thread.
Reference: https://github.com/Tencent/MMKV#quick-tutorial-1

Fix: Main thread error with initialize function

---

README.md

Refs:
* https://github.com/mrousavy/react-native-mmkv/issues/347#issuecomment-1063958167
This PR adds a clarification to the `id` config field description and default fallback behavior, which has been explained by Marc in the referenced issue.

chore: clarify the `id` field docs

---

android/src/main/cpp/MmkvHostObject.cpp
example/ios/Podfile.lock
ios/MmkvHostObject.mm
react-native-mmkv.podspec
src/MMKV.ts
src/hooks.ts

This PR uses the new API I have created in my PR (https://github.com/Tencent/MMKV/pull/828) to return `undefined` instead of `0.0` (`getNumber(..)`) or `false` (`getBoolean(..)`) virtually without any added runtime cost.
Default values of `0.0` or `false` might be misleading in some cases.
* `getNumber` now returns `undefined` instead of `0.0` if it was not found in the storage
* `getBoolean` now returns `undefined` instead of `false` if it was not found in the storage

feat: Use `undefined` as a default value (**BREAKING CHANGE**)

---

ios/MmkvHostObject.mm

fix: Fix MacOS compile by using `BOOL` instead of `bool`

---

src/createMMKV.web.ts

local storage saves values in string format. so  Boolean('false') is always true. for this method to work correctly, it should check if value is 'true' or 'false' as string and returns the condition result.
to simplify the code I just return value === 'true'

fix getBoolean on the Web

---

android/build.gradle

- React Native's Android source file directory pattern changed from version 0.69.0
- download boost from Jfrog directly (`boost-for-react-native` didn't update required version(v1.76.0))
(fyi. https://github.com/react-native-community/boost-for-react-native)
I think it may break example (I didn't test example)

fix: Fix build.gradle for RN 0.69

---

src/hooks.ts

In some rare cases, when the user passes in the same key but a different MMKV instance the hook does not update it's value:
```ts
const useMmkvList = () => {
const defaultStorage = useMMKV()
const demoStorage = useMMKV({ id: "demo" })
const [env, _] = useMMKVObject("env")
useMMKVObject("list", env.isDemoMode ? demoStorage : defaultStorage)
}
```
This PR fixes this so that the value is updated when either the key is changed, or the instance is different.
* Fixes https://github.com/mrousavy/react-native-mmkv/issues/411
* Overrides #419

fix: Update hook value if key **or instance** changes

---

docs/WRAPPER_JOTAI.md

Hey @mrousavy , thanks for the awesome library!
I just have a small change, which corrects the jotai wrapper example to use the correct function call in respect to the imports from `jotai/utils` 
Thanks!

fix: use correct function call in jotai wrapper example

---

android/build.gradle

Added support for custom download directory using `REACT_NATIVE_DOWNLOADS_DIR` environment variable. This is copied from [this PR](https://github.com/software-mansion/react-native-reanimated/pull/3552)
Fixes #436 and #455

Allowed setting custom downloads directory

---

android/build.gradle

When compiling with ReactNative<68 and building RN from source, the Android build fails:
```
Could not determine the dependencies of task ':react-native-mmkv:externalNativeBuildDebug'.
> Task with path ':ReactAndroid:packageReactNdkDebugLibsForBuck' not found in project ':react-native-mmkv'.
```
React Native only added these tasks in version 0.68: https://github.com/facebook/react-native/commit/d70555ff0e1967aa09b0f291c8ed1c5918f7a8a0
For RN<68, instead of depending on separate tasks for Debug and Release (`:ReactAndroid:packageReactNdkDebugLibsForBuck` and `:ReactAndroid:packageReactNdkReleaseLibsForBuck`) we should use the old standalone task (`:ReactAndroid:packageReactNdkLibsForBuck`).

Fix Android build for RN<68 when building from source - missing Gradle tasks

---

README.md
android/CMakeLists.txt
android/src/main/cpp/MmkvHostObject.cpp
cpp/TypedArray.cpp
cpp/TypedArray.h
example/ios/Podfile.lock
ios/Mmkv.xcodeproj/project.pbxproj
ios/MmkvHostObject.mm
package.json
react-native-mmkv.podspec
src/MMKV.ts
src/createMMKV.mock.ts
src/createMMKV.web.ts
src/createTextEncoder.ts

This PR adds support for ArrayBuffers (fixed: `Uint8Array`) for the get and set functions to MMKV.
The user can write raw binary data in the form of Uint8Arrays to the storage:
```ts
const storage = new MMKV()
const buffer = new Uint8Array([255, 255, 100, 100, 8, 8, 5])
storage.set('buffer', buffer)
```
And retrieve it again:
```ts
const storage = new MMKV()
const buffer = storage.getBuffer('buffer')
console.log(buffer)
```
To convert a `Uint8Array` to an `ArrayBuffer`:
```ts
const arrayBuffer = // ArrayBuffer...
const buffer = new Uint8Array(arrayBuffer)
// and other way around:
const buffer = storage.getBuffer('buffer')
const arrayBuffer = buffer.buffer
```
Writing a Buffer to storage involves only a single copy operation. This means it's really fast.
Reading from storage is fast as …

feat: Support setting and getting ArrayBuffers (`Uint8Array`)

---

android/build.gradle

This PR removes the deprecated gradle property `dexOptions`, which will be removed with Gradle 8.0.
Warning in Android Studio:
```
DSL element 'dexOptions' is obsolete and should be removed.
It will be removed in version 8.0 of the Android Gradle plugin.
Using it has no effect, and the AndroidGradle plugin optimizes dexing automatically.
Affected Modules: react-native-mmkv
```
Resolves #437

Remove deprecated dexOptions gradle property

---

android/build.gradle

Should resolve https://github.com/mrousavy/react-native-mmkv/issues/497#issuecomment-1384902642
Opened a PR from the GitHub Web UI for the first time since it was a one-line change.

bug: build crashes when new architecture is not enabled

---

package.json

It seems like codegen will generate duplicated files if `codegenConfig` property is missing from `package.json` (meaning all view manager delegates and interfaces will be also generated under `react-native-mmkv/android/build/generated/source/codegen/react/viewmanagers`). This results in the build failing due to multiple definitions of the same classes.
I'm not exactly sure what `jsSrcsDir` should point to in this case. It doesn't really matter as long as the library doesn't depend on the generated code, but if it points to a non-existent directory the build will fail. Since files under `src` aren't included in the npm package, I figured the `lib/module` will do. Feel free to change it if you have other ideas.
Related issue: https://github.com/software-mansion/react-native-gesture-handler/i …

Add `codegenConfig` to `package.json` to prevent generating duplicate classes

---

README.md
src/MMKV.ts

Adds a `fastWrites` property to the MMKV constructor.
* When `true`, MMKV does not overwrite previous values when calling `set`. This is faster, but uses more memory.
* When `false`, MMKV deletes the previous value before calling `set`. This makes sure the storage size is always as small as possible, with the added performance cost of one delete call before setting. 
Before this PR, MMKV behaved as if `fastWrites` was set to `true` (i.e.; fast, but use more memory). Now after this PR, `fastWrites` is `false` by default, because users were complaining in #440 that the storage size grows too big.

feat: `fastWrites` prop

---

src/createMMKV.web.ts

**I'm putting this PR up as a draft because I still need to put these changes through its paces in our codebase, but I would appreciate any feedback you might have in the interim.**
Local storage does not have a concept of separate stores in user code, this change emulates that behaviour by prefixing the keys in local storage with `id`.
This retains backwards compatibility with existing web MMKV stores by treating the the default `mmkv.default` id is as prefixless.
Fixes #520
- **How can I exercise the web code in the unit tests?**
The unit tests don't seem to exercise the `id` option, I'm open to extending the test coverage for this, but for this change it would probably also make sense to actually exercise the web code in tests.
- **Running `yarn lint` fails unexpectedly**
```
Error: …
```

feat: Support `id` on web

---

README.md

Hi 👋
One thing I'd like to update and make it future-proof for Expo specific projects is to update the installation command from `expo install...` to `npx expo install...`. Since the latter refers to the new Expo CLI, which doesn't require any global package installation. For `expo install`, people will need to install the deprecated global cli (and we are not recommending that).

docs: Update deprecated `expo install` instructions to `npx expo install`

---

android/build.gradle
android/src/main/AndroidManifest.xml

As per https://github.com/react-native-community/discussions-and-proposals/issues/671, this change is needed to support a future release of React Native.

feat(android): add support for upcoming react native 0.73

---

README.md

This pull request updates the README to add a section linking to reactotron-react-native-mmkv, a new library to automatically log writes to your MMKV storage using Reactotron.

Add reactotron-react-native-mmkv reference to README

---

src/createMMKV.web.ts

The latest version 2.10.0 added a good fallback strategy for browsers with disabled localStorage. The warning is also useful, but it tends to spam and flood the console/logs of Next.js/Node server environments. To address this, you can add a simple check to limit the console.log statement to the browser environment only.
Addresses a regression caused by https://github.com/mrousavy/react-native-mmkv/pull/533

fix: prevent console.warn spam in server environment

---

src/hooks.ts

Fixes #599.
Please read the linked issue for a detailed description of the issue being fixed here.
This change is a one-liner, nice and simple.
I had hoped to write a test to validate the change + prevent future regressions, but I didn't see a test suite. 
I didn't want to make this PR too big, so I opted to add a test suite and a relevant test in a separate PR: #600.

fix: correct behavior of function setState parameter

---

ios/MmkvModule.mm

Fix: "Failed to create MMKV instance" after reload/fast refresh with Expo Dev Client

---

react-native-mmkv.podspec

Hi Marc 👋 😄 
When using `react-native-mmkv` with latest RN RC (0.74-RC.2), iOS fails to build due to some C++ errors that looked like header issues to me. This PR changes the Podspec to use the `install_modules_dependencies` function if available which solves this issue for me.

Use install_modules_dependencies in podspec

---

docs/WRAPPER_REACT_QUERY.md

Hello!
I saw this PR got merged: https://github.com/mrousavy/react-native-mmkv/pull/642
After some post-merge discussions in that PR, we came to the conclusion that it might be good to revert the instructions to how they were before, to be more in-line with usage within React.

chore: update usage docs for react-query example

---

docs/WRAPPER_JOTAI.md

`createJSONStorage` handles `JSON.string()`/`JSON.parse()` when setting and returning the stored value. The current documentation always results in a string being returned.

docs: Update Jotai wrapper documentation to remove the double JSON.stringify() / JSON.parse()

---

README.md
example/yarn.lock
package.json
src/MMKV.ts
src/PlatformChecker.ts
src/hooks.ts
yarn.lock

`react-native-mmkv` already has automocking for Jest, but not for Vitest.
This commit adds automocking for Vitest test environments just by checking if the `VITEST_WORKER_ID` environment variable is present.
This new functionality was also documented in the README, in the "Testing with Jest or Vitest" section, formerly the "Testing with Jest" section.
This way, `MMKV` will be mocked in both Jest and Vitest test environments.

feat: add automocking in vitest

---

package/src/index.ts

Previously it was only exported as a type, causing it to be undefined in release.
- Fixes https://github.com/mrousavy/react-native-mmkv/issues/691

fix: Export `Mode` enum as value

---

package/android/CMakeLists.txt
package/android/src/main/cpp/cpp-adapter.cpp

Since the mmkv was migrated to a pure c++ turbo module, there is no longer need for the adapter which anyway includes useless code

chore: remove leftover code

---

package/.eslintrc.js
package/android/src/main/java/com/mrousavy/mmkv/MmkvPlatformContextModule.java
package/ios/MmkvPlatformContextModule.mm
package/src/MMKV.ts
package/src/NativeMmkv.ts
package/src/NativeMmkvPlatformContext.ts
package/src/createMMKV.ts
package/src/createMMKV.web.ts
package/src/hooks.ts

Adds support for using AppGroups.
This stores MMKV instances in a shared AppGroup directory - it is mostly automatic.
To do this simply add your `AppGroup` to `Info.plist`, and don't pass a `path` to `new MMKV(...)` - MMKV will then automatically use the `AppGroup` path instead.
- Fixes https://github.com/mrousavy/react-native-mmkv/issues/622
- Fixes https://github.com/mrousavy/react-native-mmkv/issues/627
- Fixes https://github.com/mrousavy/react-native-mmkv/issues/650
- Resolves https://github.com/mrousavy/react-native-mmkv/issues/702 
- Closes https://github.com/mrousavy/react-native-mmkv/pull/703
Sorry @calism2 - your PR looked good, but I felt like moving the iOS-specific code into `MmkvPlatformContext` made more sense instead of cramming it into the shared cpp constructor.

feat: Support AppGroups

---

package/.eslintrc.js
package/cpp/MmkvHostObject.cpp
package/src/Types.ts

With this change, MMKV now checks return values of `set(...)` or `recrypt(...)` and throws an error if these methods failed.
- Fixes https://github.com/mrousavy/react-native-mmkv/issues/583

feat: Throw errors if `set` or `recrypt` failed

---

package/cpp/MmkvHostObject.cpp
package/cpp/NativeMmkvModule.h

Updates cpp code to rename some variables to meet new CodeGen specifications

fix: Update cpp code to support React Native 0.75.1

---

package/src/MMKV.ts
package/src/MemoryWarningListener.ts
package/src/NativeMmkvPlatformContext.ts

This now calls `trim()` on the MMKV instance whenever a memory warning occurs. This prevents out of memory errors.
To prevent the MMKV instance from being forever held strong, we now use `WeakRef` and `FinalizationRegistry`, if they are available (RN 0.75+)

feat: Trim MMKV on memoryWarning - GC safe via `WeakRef`!

---

package/react-native-mmkv.podspec

Yolo'd this to unblock my react-native-macos app, which I am migrating to the new architecture.
With the new architecture enabled, I tested this change for macOS by running it with [react-native-test-app](https://github.com/microsoft/react-native-test-app).
I restored the podspec to the [previous code](https://github.com/mrousavy/react-native-mmkv/commit/3d0a289a7bf2ff1d67920890b9a740a435c5d39b) that was here in the history using git blame. I did not test tvOS support against this change, but I saw that #713 was open and asked for this change as well.
What else would you like to see in this PR? Examples, tests, etc.?
Also, it is unclear to me what the min versions should be in the podspec for tvOS and macOS.

fix: enable macOS and tvOS in podspec

---

package/src/MMKV.ts
package/src/MemoryWarningListener.web.ts
package/src/NativeMmkv.ts
package/src/Types.ts
package/src/createMMKV.ts
package/src/createMMKV.web.ts
package/src/hooks.ts
package/src/index.ts

This PR adds 1 new web entry point and updates imports for 2 copied types.  React-native-web will no longer be necessary to use this library with webpack/vite configurations.
In order to fix this I did have to duplicate the 2 type definitions in NativeMmkv.ts.  React Native Codegen requires those types be in the file with the spec definition.  In doing so accessing those types causes imports to react native.  For Now duplicate the types with notes so the project can be built to work on web and react native.
Starting with 3.x webpack required the addition of react-native-web to work.  
Webpack would throw errors even with react-native-web but those errors seemed to be ignored and everything worked as expected. 
Vite configuration will not ignore those errors even with react-native-web. …

fix: Improve support for web projects

---

package/cpp/MmkvHostObject.cpp

Makes all MMKV methods a bit faster by skipping the type-check after we already checked the type. Replace `asString` -> `getString`, we already checked `isString` before.

perf: Make all methods a bit faster by skipping double JSI type-check

---

package/src/Types.ts

The `readOnly` configuration property was supported on native, but was missing from the types when calling `new MMKV(...)`. This PR adds it there.
If you don't need to write to the MMKV database, creating it in `readOnly` mode is more efficient:
```ts
const instance = new MMKV({ id: 'storage', readOnly: true })
```

fix: Add `readOnly` to `new(..)` types

---

packages/react-native-mmkv/package.json

When validating data in React Native Directory, I have spotted that `react-native-mmkv` uses the package name as a package description:
Update package description to be more meaningful (copied over first sentence from the GitHub repository description), which should help the RND viewers and [improve discoverability](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#description-1) in npm registry.

chore: update package description to be more meaningful

---

docs/V4_UPGRADE_GUIDE.md
example/ios/Podfile
example/ios/Podfile.lock
packages/react-native-mmkv/NitroMmkv.podspec

Updates MMKVCore to [v2.2.4](https://github.com/Tencent/MMKV/releases/tag/v2.2.4), which now includes my PR to define modules. This now removes the need from users to add it to their `Podfile`s, and was the last change needed to make V4 beta stable.

feat: Update MMKVCore to 2.2.4 which defines Modules
