README.md
Just thought it would be cool to have an example for `mobx` as well :)
=> [docs] mobx-persist-store example added

android/build.gradle
Please try this in a non monorepo build. Even if it should work fine
=> fix(android): fix monorepo build

README.md
=> Fix documentation for clearAll

README.md, docs/WRAPPER_MOBXPERSIST.md
Adding documentation responding to #269
=> Wrapper for mobx-persist library

android/src/main/cpp/MmkvHostObject.cpp, ios/MmkvHostObject.mm, src/MMKV.ts, src/createMMKV.web.ts
```ts
const storage = new MMKV({ id: 'my.test.storage' })
storage.encrypt('my-private-key') // <-- encrypt with key 'my-private-key'
storage.set('test', 'works!')
storage.encrypt(undefined) // <-- remove encryption
storage.set('test', 'still works!')
```
closes: #179
=> feat: Re-Crypt an existing Storage instance (`storage.encrypt(..)`)

ios/MmkvHostObject.mm, macos/Mmkv.xcodeproj/project.pbxproj, react-native-mmkv.podspec
add support for https://github.com/microsoft/react-native-macos
=> feat: Add MacOS support

README.md, docs/WRAPPER_ZUSTAND_PERSIST_MIDDLEWARE.md
Added wrapper for using MMKV with zustand.
=> add wrapper for zustand persist-middleware

src/MMKV.ts
=> fix: Fix `setImmediate`/`unstable_batchedUpdates` delaying listener execution

README.md, example/package.json, example/test/MMKV.test.ts, example/tsconfig.json, example/yarn.lock, src/MMKV.ts, src/PlatformChecker.ts, src/createMMKV.mock.ts, tsconfig.build.json, tsconfig.json
When running in a test environment, use a mock MMKV instance that utilises an underlying `Map` structure. This allows tests on this package to work without having to manually define mocks or any jest setup files.
Inspired by #367.
=> Automocking in test environment

package.json
=> Buffer support: add cpp directory to package

.github/workflows/validate-cpp.yml, android/src/main/cpp/cpp-adapter.cpp, cpp/TypedArray.cpp, cpp/TypedArray.h, example/ios/Podfile.lock, ios/MmkvModule.mm, src/hooks.ts
=> fix: Destroy ArrayBuffer cache on Runtime reload

android/build.gradle
Should fix https://github.com/mrousavy/react-native-mmkv/issues/510
=> fix: detox 0.71 error duplicated libc++_shared.so

package.json, yarn.lock
More context: https://github.com/expo/expo/issues/21276
=> fix: expo warnings in newest expo

src/createMMKV.web.ts
=> fix: Clean up `id` on Web

ios/MmkvHostObject.mm, ios/MmkvModule.mm, src/MMKV.ts
Replicating existing PR https://github.com/mrousavy/react-native-mmkv/pull/402 and following on open comments as would like to use this change in my code.
=> iOS/app-group MMKV MultiProcess mode

android/src/main/AndroidManifest.xml
This PR revert AndroidManifest  file to add support RN 0.71
=> revert(android): revert change AndroidManifest to support RN < 0.71

android/build.gradle
Added support for AGP version 8 and above to fix build issues on RN v0.73
=> feat: added support for AGP>=8

src/createMMKV.web.ts
Have to make sure to remove the prefix from the keys before returning them.
=> fix: getAllKeys on web

android/build.gradle, android/src/hasNamespace/AndroidManifest.xml
Fixes https://github.com/mrousavy/react-native-mmkv/issues/592
=> fix: Fix `namespace`/`package` error in `AndroidManifest` on AGP 8/RN 0.73

.github/workflows/build-ios.yml, package/android/src/main/cpp/AndroidLogger.cpp, package/cpp/MmkvHostObject.cpp, package/cpp/MmkvLogger.h, package/cpp/NativeMmkvModule.cpp, package/ios/AppleLogger.mm, package/package.json
Logger.h could cause conflicts with other C++ files.
=> chore: Rename `Logger.h` to `MmkvLogger.h`

docs/WRAPPER_REACT_QUERY.md
fixed syntax highlight in readme for wrapper for react query
=> [DOCS] fixed syntax highlight in readme for wrapper for react query

docs/WRAPPER_JOTAI.md
See https://jotai.org/docs/utilities/storage#parameters
The 4th parameter should be a subscribe function. The clearAll function does not make sense here.
=> Use subscribe instead of clearAll

package/src/MMKV.ts, package/src/Types.ts, package/src/createMMKV.web.ts, package/src/hooks.ts
Previously it was `Uint8Array`, now it's `ArrayBufferLike`.
=> fix: Fix `getBuffer` type for web. It's `.buffer`

README.md, packages/react-native-mmkv/android/src/main/java/com/margelo/nitro/mmkv/HybridMMKVPlatformContext.kt, packages/react-native-mmkv/ios/HybridMMKVPlatformContext.swift, packages/react-native-mmkv/nitrogen/generated/android/c++/JHybridMMKVPlatformContextSpec.cpp, packages/react-native-mmkv/nitrogen/generated/android/c++/JHybridMMKVPlatformContextSpec.hpp, packages/react-native-mmkv/nitrogen/generated/android/kotlin/com/margelo/nitro/mmkv/HybridMMKVPlatformContextSpec.kt, packages/react-native-mmkv/nitrogen/generated/ios/NitroMmkv-Swift-Cxx-Bridge.hpp, packages/react-native-mmkv/nitrogen/generated/ios/NitroMmkv-Swift-Cxx-Umbrella.hpp, packages/react-native-mmkv/nitrogen/generated/ios/c++/HybridMMKVPlatformContextSpecSwift.hpp, packages/react-native-mmkv/nitrogen/generated/ios/swift/HybridMMKVPlatformContextSpec.swift, packages/react-native-mmkv/nitrogen/generated/ios/swift/HybridMMKVPlatformContextSpec_cxx.swift, packages/react-native-mmkv/nitrogen/generated/shared/c++/HybridMMKVPlatformContextSpec.hpp, packages/react-native-mmkv/src/specs/MMKVPlatformContext.nitro.ts
Breaking change: In Info.plist, rename `AppGroup` to `AppGroupIdentifier`
=> feat: Implement `AppGroup`

packages/react-native-mmkv/src/createMMKV/createMMKV.web.ts
- Fixes https://github.com/mrousavy/react-native-mmkv/issues/892
=> fix: Fix optional `config` on Web
